### ISSUE TITLE
Need to optimize the memory usage of get user image methods

### ISSUE THREAD

**Issue by aaujayasena** [wso2/identity-content-repository#3]
Currently, memory usage is high in get user image method according to the performance test. 
Suggested solution: Change the implementation using java channel API.

Priority: High
Severity: Critical
Version: 1.01
Type: Improvement

![image](https://user-images.githubusercontent.com/39077751/70791916-1dd96680-1dbe-11ea-86ea-95b0585a78c4.png)

**Comment by nilasini** [comment]
Moved to https://github.com/wso2/product-is/issues/7141
