### ISSUE TITLE
Optimize the CPU usage in get user image method

### ISSUE THREAD

**Issue by aaujayasena** [wso2/identity-content-repository#4]
Priority: Law
Severity: Critical
Version: 1.01
Type: Improvement

According to the performance test ,high percentage of CPU usage allocation for sun security provider package used at get user image method.  It's almost 73% . 

Suggested solution: Look for a effective library set other than sun security  package. 

![image](https://user-images.githubusercontent.com/39077751/70794459-aa3a5800-1dc3-11ea-90b4-67fc34667824.png)

**Comment by ruwanta** [comment]
This is not related to image service. This is a problem with all services, and HTMP pages on product level. Better move it to product level.

**Comment by aaujayasena** [comment]
Moved the issue at IS product repository. This issue will be track on issue [1]. So closing the issue. 

[1] https://github.com/wso2/product-is/issues/7081
